sdf <- sparklyr::sdf_copy_to(sc,
  data.frame(
    wkt = "POLYGON ((0 0, 0 2, 1 2, 1 0, 0 0))",
    point_wkt = "POINT (1 1)" 
  )
)

sdf <- mutate(sdf, "st_area" = st_area(wkt))
sdf <- mutate(sdf, "st_length" = st_length(wkt))
sdf <- mutate(sdf, "st_perimeter" =  st_perimeter(wkt))
sdf <- mutate(sdf, "st_convexhull" = st_convexhull(wkt))
sdf <- mutate(sdf, "st_dump" = st_dump(wkt))
sdf <- mutate(sdf, "st_translate" =  st_translate(wkt, lit(1), lit(1)))
sdf <- mutate(sdf, "st_scale" =  st_scale(wkt, lit(1), lit(1)))
sdf <- mutate(sdf, "st_rotate" = st_rotate(wkt, lit(1)))
sdf <- mutate(sdf, "st_centroid2D" = st_centroid2D(wkt))
#sdf<- mutate(sdf, "st_centroid3D" = st_centroid3D(wkt))
sdf <- mutate(sdf, "st_length" = st_length(wkt))
sdf <- mutate(sdf, "st_isvalid" =  st_isvalid(wkt))
sdf <- mutate(sdf, "st_intersects" = st_intersects(wkt, wkt))
#sdf<- mutate(sdf, "st_intersection" = st_intersection(wkt, wkt))
sdf <- mutate(sdf, "st_geometrytype" = st_geometrytype(wkt))
sdf <- mutate(sdf, "st_isvalid" =  st_isvalid(wkt))
sdf <- mutate(sdf, "st_xmin" = st_xmin(wkt))
sdf <- mutate(sdf, "st_xmax" = st_xmax(wkt))
sdf <- mutate(sdf, "st_ymin" = st_ymin(wkt))
sdf <- mutate(sdf, "st_ymax" = st_ymax(wkt))
sdf <- mutate(sdf, "st_zmin" = st_zmin(wkt))
sdf <- mutate(sdf, "st_zmax" = st_zmax(wkt))
sdf <- mutate(sdf, "flatten_polygons" =  flatten_polygons(wkt))
sdf <- mutate(sdf, "point_index_lonlat" =  point_index_lonlat(1,1, 1L))
sdf <- mutate(sdf, "point_index_geom" =  point_index_geom(point_wkt, 1L))
sdf <- mutate(sdf, "index_geometry" =  index_geometry( 1L))
sdf <- mutate(sdf, "polyfill" =  polyfill(wkt, 1L))
sdf <- mutate(sdf, "mosaic_explode" =  mosaic_explode(wkt, 1L)))
sdf <- mutate(sdf, "mosaicfill" =  mosaicfill(wkt, lit(1L)))
sdf <- mutate(sdf, "geom_with_srid" =  st_setsrid(st_geomfromwkt(wkt), 4326L))
sdf <- mutate(sdf, "srid_check" =  st_srid(column("geom_with_srid")))
sdf <- mutate(sdf, "transformed_geom" =  st_transform(column("geom_with_srid"), lit(3857L)))
