name: Build mosaic project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        dbr: [9.1LTS]
        python: [3.8.8, 3.8.10]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '8'
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - env:
        DBR_VERSION: ${{ matrix.dbr }}
      run: mvn -q -Druntime=${DBR_VERSION} clean install
    - run: mkdir staging
    - run: cp target/mosaic*.jar staging
    - run: cp target/mosaic-*-jar-with-dependencies.jar python/mosaic
    - run: (cd python;pip install -e .[dev];python -m build)
    - run: cp python/dist/*.whl staging
    - uses: actions/upload-artifact@v2
      with:
        name: artefacts
        path: staging