name: Pages
on:
  push:
    branches:
    - documentation
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install pandoc
      run: sudo apt-get install pandoc
    - uses: actions/setup-python@v2
    - uses: actions/checkout@v2
      with:
        ref: documentation
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with:
        documentation_path: docs/python/source
        requirements_path: docs/python/requirements.txt
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages