package com.databricks.labs.mosaic.core.raster.api

object FormatLookup {

    // ShortDriverName -> FormatExtension
    val formats: Map[String, String] = Map(
        "AAIGrid" -> "asc",
        "ACE2" -> "ace2",
        "ADRG" -> "gen",
        "AIG" -> "aig",
        "AIRSAR" -> "airsar",
        "ARCGEN" -> "gen",
        "ARG" -> "arg",
        "BLX" -> "blx",
        "BMP" -> "bmp",
        "BT" -> "bt",
        "CAD" -> "dwg",
        "CEOS" -> "ceos",
        "COASP" -> "coasp",
        "COG" -> "tif",
        "COSAR" -> "cosar",
        "CPG" -> "cpg",
        "CSW" -> "csw",
        "CTG" -> "ctg",
        "DB2ODBC" -> "db2",
        "DERIVED" -> "derived",
        "DGN" -> "dgn",
        "DIMAP" -> "dim",
        "DIPEx" -> "dipex",
        "DOQ1" -> "doq1",
        "DOQ2" -> "doq2",
        "DTED" -> "dt0",
        "DXF" -> "dxf",
        "ECRGTOC" -> "toc",
        "ECRGTP" -> "ecrgtp",
        "EEDA" -> "eeda",
        "EIR" -> "eir",
        "ELAS" -> "elas",
        "ENVI" -> "hdr",
        "ERS" -> "ers",
        "ESAT" -> "esat",
        "ESRI Shapefile" -> "shp",
        "ESRI" -> "ers",
        "FAST" -> "fst",
        "FIT" -> "fit",
        "FITS" -> "fits",
        "GFF" -> "gff",
        "GIF" -> "gif",
        "GLOBE" -> "globe",
        "GMT" -> "gmt",
        "GNM" -> "gnm",
        "GRASSASCIIGrid" -> "asc",
        "GRASS" -> "grass",
        "GRIB" -> "grb",
        "GTiff" -> "tif",
        "GXF" -> "gxf",
        "HDF4" -> "hdf4",
        "HDF5" -> "hdf5",
        "HF2" -> "hf2",
        "HFA" -> "img",
        "HTTP" -> "http",
        "IDRISI" -> "rst",
        "ILWIS" -> "mpr",
        "INGR" -> "grd",
        "IRIS" -> "ppm",
        "ISIS2" -> "cub",
        "ISIS3" -> "cub",
        "JDEM" -> "mem",
        "JPEG2000" -> "jp2",
        "JPEG" -> "jpg",
        "JP2OpenJPEG" -> "jp2",
        "KMLSUPEROVERLAY" -> "kml",
        "LAN" -> "lan",
        "LCP" -> "lcp",
        "L1B" -> "l1b",
        "MBTiles" -> "mbtiles",
        "MEM" -> "mem",
        "MFF" -> "mff",
        "MG4Lidar" -> "mg4l",
        "MRF" -> "mrf",
        "MSGN" -> "msgn",
        "NDF" -> "ndf",
        "NITF" -> "ntf",
        "NTv2" -> "gsb",
        "ODBC" -> "odbc",
        "OGR_GMT" -> "gmt",
        "OGR_PDS" -> "pds",
        "OGR_SDTS" -> "sdts",
        "OGR_VRT" -> "vrt",
        "OGR" -> "shp",
        "OpenAir" -> "oar",
        "PCIDSK" -> "pix",
        "PCRaster" -> "map",
        "PDF" -> "pdf",
        "PDS" -> "pds",
        "PGDUMP" -> "pgdump",
        "PGeo" -> "mdb",
        "PLMOSAIC" -> "mosaic",
        "PNG" -> "png",
        "PostgreSQL" -> "pg",
        "R" -> "r",
        "RDA" -> "rda",
        "RIK" -> "rik",
        "RMF" -> "rmf",
        "ROI_PAC" -> "rsc",
        "RPFTOC" -> "toc",
        "RS2" -> "rs2",
        "RST" -> "rst",
        "SAGA" -> "sdat",
        "SAR_CEOS" -> "ceos",
        "SAR_SG" -> "sgm",
        "SDTS" -> "sdts",
        "SEGUKOOA" -> "dat",
        "SEGY" -> "segy",
        "Sentinel2" -> "jp2",
        "SRTMHGT" -> "hgt",
        "SQLite" -> "sqlite",
        "SUA" -> "sua",
        "SVG" -> "svg",
        "TIGER" -> "tiger",
        "TIL" -> "til",
        "TSX" -> "tsx",
        "USGSDEM" -> "dem",
        "VDV" -> "vdv",
        "VICAR" -> "vicar",
        "VFK" -> "vfk",
        "VRT" -> "vrt",
        "WCS" -> "wcs",
        "WFS" -> "wfs",
        "WMS" -> "wms",
        "XLS" -> "xls",
        "XLSX" -> "xlsx",
        "XPlane" -> "bin",
        "netCDF" -> "nc",
        "Zarr" -> "zarr"
    )

    val COMMON_URI_TOKENS = Seq(
        "BMP",
        "COG",
        "ESRI Shapefile",
        "GIF",
        "GRIB:",
        "GTiff:",
        "HDF4:",
        "HDF5:",
        "HTTP:",
        "JPEG2000:",
        "JPEG:",
        "JP2OpenJPEG:",
        "NITF:",
        "OGR_GMT:",
        "OGR_PDS:",
        "OGR_SDTS:",
        "OGR_VRT:",
        "OGR", // <- shapefile
        "PDF:",
        "PNG:",
        "SVG:",
        "XPM:",
        "netCDF:",
        "Zarr:"
    )


    // from `gdalinfo --formats`
    val ALL_RASTER_URI_TOKENS = Seq(
        "VRT:",
        "DERIVED:",
        "GTiff:",
        "COG:",
        "NITF:",
        "RPFTOC:",
        "ECRGTOC:",
        "HFA:",
        "SAR_CEOS:",
        "CEOS:",
        "JAXAPALSAR:",
        "GFF:",
        "ELAS:",
        "ESRIC:",
        "AIG:",
        "AAIGrid:",
        "GRASSASCIIGrid:",
        "ISG:",
        "SDTS:",
        "DTED:",
        "PNG:",
        "JPEG:",
        "MEM:",
        "JDEM:",
        "GIF:",
        "BIGGIF:",
        "ESAT:",
        "FITS:",
        "BSB:",
        "XPM:",
        "BMP:",
        "DIMAP:",
        "AirSAR:",
        "RS2:",
        "SAFE:",
        "PCIDSK:",
        "PCRaster:",
        "ILWIS:",
        "SGI:",
        "SRTMHGT:",
        "Leveller:",
        "Terragen:",
        "GMT:",
        "netCDF:",
        "HDF4:",
        "HDF4Image:",
        "ISIS3:",
        "ISIS2:",
        "PDS:",
        "PDS4:",
        "VICAR:",
        "TIL:",
        "ERS:",
        "JP2OpenJPEG:",
        "L1B:",
        "FIT:",
        "GRIB:",
        "RMF:",
        "WCS:",
        "WMS:",
        "MSGN:",
        "RST:",
        "INGR:",
        "GSAG:",
        "GSBG:",
        "GS7BG:",
        "COSAR:",
        "TSX:",
        "COASP:",
        "R:",
        "MAP:",
        "KMLSUPEROVERLAY:",
        "WEBP:",
        "PDF:",
        "Rasterlite:",
        "MBTiles:",
        "PLMOSAIC:",
        "CALS:",
        "WMTS:",
        "SENTINEL2:",
        "MRF:",
        "PNM:",
        "DOQ1:",
        "DOQ2:",
        "PAux:",
        "MFF:",
        "MFF2:",
        "FujiBAS:",
        "GSC:",
        "FAST:",
        "BT:",
        "LAN:",
        "CPG:",
        "IDA:",
        "NDF:",
        "EIR:",
        "DIPEx:",
        "LCP:",
        "GTX:",
        "LOSLAS:",
        "NTv2:",
        "CTable2:",
        "ACE2:",
        "SNODAS:",
        "KRO:",
        "ROI_PAC:",
        "RRASTER:",
        "BYN:",
        "ARG:",
        "RIK:",
        "USGSDEM:",
        "GXF:",
        "BAG:",
        "HDF5:",
        "HDF5Image:",
        "NWT_GRD:",
        "NWT_GRC:",
        "ADRG:",
        "SRP:",
        "BLX:",
        "PostGISRaster:",
        "SAGA:",
        "XYZ:",
        "HF2:",
        "JPEGLS:",
        "OZI:",
        "CTG:",
        "ZMap:",
        "NGSGEOID:",
        "IRIS:",
        "PRF:",
        "RDA:",
        "EEDAI:",
        "DAAS:",
        "SIGDEM:",
        "HEIF:",
        "TGA:",
        "OGCAPI:",
        "STACTA:",
        "STACIT:",
        "GPKG:",
        "CAD:",
        "PLSCENES:",
        "NGW:",
        "GenBin:",
        "ENVI:",
        "EHdr:",
        "ISCE:",
        "Zarr:",
        "HTTP:"
    )

    // from `ogrinfo --formats`
    val ALL_VECTOR_URI_TOKENS = Seq(
        "FITS:",
        "PCIDSK:",
        "netCDF:",
        "PDS4:",
        "VICAR:",
        "JP2OpenJPEG:",
        "PDF:",
        "MBTiles:",
        "BAG:",
        "EEDA:",
        "OGCAPI:",
        "ESRI Shapefile:", // HAS A SPACE?
        "MapInfo File:",
        //"UK .NTF:", // COMMENTED OUT DUE TO CONFUSION
        "LVBAG:",
        "OGR_SDTS:",
        "S57:",
        "DGN:",
        "OGR_VRT:",
        "REC:",
        "Memory:",
        "CSV:",
        "NAS:",
        "GML:",
        "GPX:",
        "LIBKML:",
        "KML:",
        "GeoJSON:",
        "GeoJSONSeq:",
        "ESRIJSON:",
        "TopoJSON:",
        "Interlis 1:", // HAS A SPACE?
        "Interlis 2:", // HAS A SPACE?
        "OGR_GMT:",
        "GPKG:",
        "SQLite:",
        "ODBC:",
        "WAsP:",
        "PGeo:",
        "MSSQLSpatial:",
        "OGR_OGDI:",
        "PostgreSQL:",
        "MySQL:",
        "OpenFileGDB:",
        "DXF:",
        "CAD:",
        "FlatGeobuf:",
        "Geoconcept:",
        "GeoRSS:",
        "GPSTrackMaker:",
        "VFK:",
        "PGDUMP:",
        "OSM:",
        "GPSBabel:",
        "OGR_PDS:",
        "WFS:",
        "OAPIF:",
        "SOSI:",
        "Geomedia:",
        "EDIGEO:",
        "SVG:",
        "CouchDB:",
        "Cloudant:",
        "Idrisi:",
        "ARCGEN:",
        "XLS:",
        "ODS:",
        "XLSX:",
        "Elasticsearch:",
        "Walk:",
        "Carto:",
        "AmigoCloud:",
        "SXF:",
        "Selafin:",
        "JML:",
        "PLSCENES:",
        "CSW:",
        "VDV:",
        "GMLAS:",
        "MVT:",
        "NGW:",
        "MapML:",
        "TIGER:",
        "AVCBin:",
        "AVCE00:",
        "HTTP:"
    )

}
