name: build mosaic R
description: build mosaic R
runs:
  using: "composite"
  steps:
    - name: Setup R build environment
      run: |
        sudo apt-get update && sudo apt-get install -y curl libcurl4-openssl-dev pkg-config libharfbuzz-dev libfribidi-dev 
    - name: Download and unpack Spark
      run: |
        mkdir -p /usr/spark-tar
        wget -P /usr/spark-tar https://archive.apache.org/dist/spark/spark-3.2.1/spark-3.2.1-bin-hadoop2.7.tgz 
        mkdir /usr/spark
        tar zxvf /usr/spark-tar/spark-3.2.1-bin-hadoop2.7.tgz -C /usr/spark
        SPARK_HOME = /usr/spark/spark-3.2.1-bin-hadoop2.7


    - name: Build R package
      run: |
        cd R/sparkR-mosaic
        mkdir -p /usr/lib/R/site-library
        sudo chown -R $USER: /usr/lib/R/site-library
        Rscript --vanilla build_r_package.R
    - name: Test R package
      run: |
        cd R/sparkR-mosaic
        Rscript --vanilla tests.R
    - name: Copy R artifacts to GH Actions run
      run: |
        cp R/sparkR-mosaic/*.tar.gz staging
