name: build mosaic R
description: build mosaic R
runs:
  using: "composite"
  steps:
    - name: Setup R build environment
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y curl libcurl4-openssl-dev pkg-config libharfbuzz-dev libfribidi-dev
    - name: Create download location for Spark
      shell: bash
      run: |
        sudo mkdir -p /usr/spark-download/unzipped
        sudo mkdir -p /usr/spark-download/raw
        sudo chown -R $USER: /usr/spark-download/
    - name: Cache Spark download
      id: cache-spark
      uses: actions/cache@v3
      with:
        path: /usr/spark-download/unzipped
        key: r_build-spark
    - if: ${{ steps.cache-spark.outputs.cache-hit != 'true' }}
      name: Download and unpack Spark
      shell: bash
      run: |
        wget -P /usr/spark-download/raw https://archive.apache.org/dist/spark/spark-3.2.1/spark-3.2.1-bin-hadoop2.7.tgz
        tar zxvf /usr/spark-download/raw/spark-3.2.1-bin-hadoop2.7.tgz -C /usr/spark-download/unzipped
    - name: Create R environment
      shell: bash
      run: |
        sudo mkdir -p /usr/lib/R/site-library
        sudo chown -R $USER: /usr/lib/R/site-library
#    - name: Cache R packages download
#      id: cache-rlibs
#      uses: actions/cache@v3
#      with:
#        path: /usr/lib/R/site-library
#        key: r_build-rlibs
#    - if: ${{ steps.cache-rlibs.outputs.cache-hit != 'true' }}
#      name: Install R dependencies
#      shell: bash
#      run: |
#        cd R
#        Rscript --vanilla install_deps.R
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.R }}
        use-public-rspm: true
    - name: Install R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache: true
        extra-packages: |
          any::pkgbuild
          any::roxygen2
          any::sparklyr
    - name: Generate R bindings
      shell: bash
      run: |
        cd R
        Rscript --vanilla generate_R_bindings.R ../src/main/scala/com/databricks/labs/mosaic/functions/MosaicContext.scala
    - name: Build R docs
      shell: bash
      run: |
        cd R
        Rscript --vanilla generate_docs.R
    - name: Build R package
      shell: bash
      run: |
        cd R
        Rscript --vanilla build_r_package.R
    - name: Test R package
      shell: bash
      run: |
        cd R/sparkR-mosaic
        Rscript --vanilla tests.R
    - name: Copy R artifacts to GH Actions run
      shell: bash
      run: |
        cp R/sparkR-mosaic/*.tar.gz staging
        cp R/sparklyr-mosaic/*.tar.gz staging
