name: build mosaic scala
description: build mosaic scala
inputs: 
  skip_tests:
    description: 'Skip Scala Tests? true or false'
    default: 'false'
runs:
  using: "composite"
  steps:
        - name: Configure JDK
          uses: actions/setup-java@v2
          with:
            java-version: '8'
            distribution: 'zulu'
        - name: Configure python interpreter
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python }}
        - name: Add packaged GDAL dependencies
          shell: bash
          run : |
            apt-add-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-backports main universe multiverse restricted"
            apt-add-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-updates main universe multiverse restricted"
            apt-add-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-security main multiverse restricted universe"
            apt-add-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main multiverse restricted universe"
            apt-get update -y
            apt-get install -y unixodbc libcurl3-gnutls libsnappy-dev libopenjp2-7
            apt-get install -y gdal-bin libgdal-dev python3-gdal
            pip install --upgrade pip
            pip install GDAL==${{ matrix.gdal }}
            wget -P /usr/lib -nc https://github.com/databrickslabs/mosaic/raw/main/src/main/resources/gdal/ubuntu/libgdalalljni.so
            wget -P /usr/lib -nc https://github.com/databrickslabs/mosaic/raw/main/src/main/resources/gdal/ubuntu/libgdalalljni.so.30
            #wget -P /usr/lib -nc https://github.com/databrickslabs/mosaic/raw/main/src/main/resources/gdal/ubuntu/libgdalalljni.so.30.0.3
        - name: Test and build the scala JAR - skip tests is false
          if: inputs.skip_tests == 'false'
          shell: bash
          run: sudo mvn -q clean install
        - name: Build the scala JAR - skip tests is true
          if: inputs.skip_tests == 'true'
          shell: bash
          run: sudo mvn -q clean install -DskipTests -Dscoverage.skip
        - name: Publish test coverage
          if: inputs.skip_tests == 'false'
          uses: codecov/codecov-action@v1
        - name: Copy Scala artifacts to GH Actions run
          shell: bash
          run: |
            mkdir staging
            cp target/mosaic*.jar staging
