name: build mosaic scala
description: build mosaic scala
inputs: 
  skip_tests:
    description: "Run Scala Tests? true or false"
    default: "false"
runs:
  using: "composite"
  if: inputs.skip_tests == "false"
  steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Configure JDK
          uses: actions/setup-java@v2
          with:
            java-version: '8'
            distribution: 'zulu'
        - name: Test and build the scala JAR
          run: mvn -q clean install
        - name: Publish test coverage
          uses: codecov/codecov-action@v1
        - name: Copy Scala artifacts to GH Actions run
          run: |
            mkdir staging
            cp target/mosaic*.jar staging
  if: inputs.skip_tests == "true"
  steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Configure JDK
          uses: actions/setup-java@v2
          with:
            java-version: '8'
            distribution: 'zulu'
        - name: Test and build the scala JAR
          run: mvn -q clean install -DskipTests
        - name: Publish test coverage
          uses: codecov/codecov-action@v1
        - name: Copy Scala artifacts to GH Actions run
          run: |
            mkdir staging
            cp target/mosaic*.jar staging
    