[metadata]
name = dblabs-vectorx
author = Databricks
version = attr: vectorx.__version__
description = VectorX: A high-performance vector processing library for Apache Spark.
url = https://github.com/databrickslabs/mosaic # TODO: rename when new URL is available
long_description = file: README.md
long_description_content_type = text/markdown
license = Databricks License
classifiers =
    License :: Other/Proprietary License
    Topic :: Scientific/Engineering :: GIS
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.12

[options]
packages = find:
python_requires = <3.13,>=3.10
install_requires =
    pyspark>=4.0.0

[options.package_data]
vectorx =
    lib/*.jar
    resources/*.png

[options.extras_require]
dev =
    isort
    black
    build

[isort]
multi_line_output=3
include_trailing_comma=True
force_grid_wrap=0
use_parentheses=True
line_length=88
known_first_party=vectorx
default_section=THIRDPARTY

[flake8]
ignore = E203, E266, E501, W503
max-line-length = 88
max-complexity = 20
select = B,C,E,F,W,T4
exclude = .git,__pycache__,docs/conf.py,dist

[mypy]
files=vectorx
ignore_missing_imports=true
