name: cleanup build
description: cleanup build
runs:
  using: "composite"
  steps:
    - name: Remove tmp files
      shell: bash
      run : |
        # [1] pre-clean
        # - make dirs (just in case)
        # - get counts
        mkdir -p /tmp/mosaic_tmp
        mkdir -p /dbfs/checkpoint/mosaic_tmp
        sudo echo "files (pre-clean) -> # $(find /tmp/mosaic_tmp | wc -l) in '/tmp/mosaic_tmp'"
        sudo echo "files (pre-clean) -> # $(find /dbfs/checkpoint/mosaic_tmp | wc -l) in '/dbfs/checkpoint/mosaic_tmp'"
        # [2] remove local tmp files
        sudo echo "... cleaning '/tmp/mosaic_tmp'"
        sudo rm -rf /tmp/mosaic_tmp/*
        # [3] remove pseudo fuse files
        sudo echo "... cleaning '/dbfs/checkpoint/mosaic_tmp'"
        sudo rm -rf /dbfs/checkpoint/mosaic_tmp/*
        # [4] post-clean
        # - get counts
        sudo echo "files (post-clean) -> # $(find /tmp/mosaic_tmp | wc -l) in '/tmp/mosaic_tmp'"
        sudo echo "files (post-clean) -> # $(find /dbfs/checkpoint/mosaic_tmp | wc -l) in '/dbfs/checkpoint/mosaic_tmp'"
