name: build mosaic python
description: build mosaic python
runs:
  using: "composite"
  steps:
    - name: Configure python interpreter
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install python dependencies
      run: |
        cd python
        pip install build wheel pyspark==${{ matrix.spark }}
        pip install .
    - name: Test and build python package
      run: |
        cd python
        python -m unittest
        python -m build
    - name: Copy python artifacts to GH Actions run
      run: cp python/dist/*.whl staging