name: upload mosaic artefacts
description: upload mosaic artefacts
runs:
  using: "composite"
  steps:
    - name: upload artefacts
      uses: actions/upload-artifact@v3
      with:
        name: artefacts
        path: staging/*
