name: build_scala
on:
  push:
    branches:
      - "scala/**"

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        python: [ 3.10.12 ]
        numpy: [ 1.22.4 ]
        gdal: [ 3.4.1 ]
        spark: [ 3.4.0 ]
        R: [ 4.2.2 ]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: build scala with tests
        uses: ./.github/actions/scala_build
      - name: upload artefacts
        uses: ./.github/actions/upload_artefacts
      - name: Publish test coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
