name: build_R
# build for R, skip scala tests and python build
on:
  push:
    branches:
      - "r/*"
      - "R/*"
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        python: [ 3.8.10 ]
        spark: [ 3.2.1 ]
        R: [ 4.1.2 ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/scala_build@v1
        with: 
          skip_tests: "true"
      - uses: ./.github/actions/r_build@v1
      - uses: ./.github/actions/upload_artifacts_build@v1