name: publish python package to pypi
on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Build project and publish to PyPI
    runs-on: ubuntu-24.04
    environment: release
    permissions:
      # Used to authenticate to PyPI via OIDC and sign the release's artifacts with sigstore-python.
      id-token: write
      # Used to attach signing artifacts to the published release.
      contents: write
    strategy:
      matrix:
        python: [ 3.12.3 ]
        pytest: [8.4.2]
        numpy: [ 2.1.3 ]
        gdal: [ 3.11.4 ]
        spark: [ 4.0.0 ]
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: build scala
        uses: ./.github/actions/scala_build
      - name: build python
        uses: ./.github/actions/python_build

      # As of DEC, 2025 v1 is the latest
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: python/geobrix/dist/
